### ISSUE TITLE
Supported client wlan chipsets?

### ISSUE THREAD

**Issue by eriktar** [aanarchyy/bully#1]
Can you provide a list of supported client wlan cards?  I'm running ubuntu 15.04 with this network card:
`03:00.0 Network controller: Qualcomm Atheros AR9287 Wireless Network Adapter (PCI-Express) (rev 01)`

I'm getting this output which suggests that my network card is not compatible
```
root@monitor03:~/src/bully-master/src# ./bully -b 88:41:FC:56:4C:C9 wlan0
[!] Bully v1.1 - WPS vulnerability assessment utility
[P] Modified for pixiewps by AAnarchYY(aanarchyy@gmail.com)
[X] Unknown frequency '681831424' reported by interface 'wlan0'
[!] Using '60:d8:19:26:94:e5' for the source MAC address
[+] Datalink type set to '1', radiotap headers not present
[+] Scanning for beacon from '88:41:fc:56:4c:c9' on channel 'unknown'
[+] Switching interface 'wlan0' to channel '1'
[!] ioctl(SIOCSIWFREQ) on 'wlan0' failed with '-1'
[X] Unable to set channel on 'wlan0', exiting

```

And even better, will you support that network card?

**Comment by aanarchyy** [comment]
Any chipset that supports injection will work.

`[!] ioctl(SIOCSIWFREQ) on 'wlan0' failed with '-1'`

That error usually means you either have the interface still "up", or not in monitor mode.
