### ISSUE TITLE
Make error #10--Yet Another Make error

### ISSUE THREAD

**Issue by boinkitsbroken** [aanarchyy/bully#10]
========BEGIN ERROR LOG========
root@i-BrokeIT:~/master/bully-master/src# make
cc -I`pwd` -I`pwd`/utils/ -I`pwd`/tls/ -I`pwd`/wps/ -I`pwd`/crypto/ -I`pwd`/common/ -o bully bully.c -lpcap -lssl -lcrypto
In file included from bully.c:65:0:
crypto/crypto_openssl.c: In function ‘openssl_digest_vector’:
crypto/crypto_openssl.c:81:13: error: storage size of ‘ctx’ isn’t known
  EVP_MD_CTX ctx;
             ^~~
crypto/crypto_openssl.c: In function ‘rc4_skip’:
crypto/crypto_openssl.c:148:17: error: storage size of ‘ctx’ isn’t known
  EVP_CIPHER_CTX ctx;
                 ^~~
crypto/crypto_openssl.c: At top level:
crypto/crypto_openssl.c:301:17: error: field ‘enc’ has incomplete type
  EVP_CIPHER_CTX enc;
                 ^~~
crypto/crypto_openssl.c:302:17: error: field ‘dec’ has incomplete type
  EVP_CIPHER_CTX dec;
                 ^~~
crypto/crypto_openssl.c: In function ‘dh5_init’:
crypto/crypto_openssl.c:426:4: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
  dh->g = BN_new();
    ^~
In file included from bully.c:89:0:
80211.c: In function ‘reassoc’:
80211.c:328:16: warning: implicit declaration of function ‘set_chan’ [-Wimplicit-function-declaration]
     G->chanx = set_chan(G, tag->data[0]);
                ^~~~~~~~
80211.c:356:16: warning: implicit declaration of function ‘next_chan’ [-Wimplicit-function-declaration]
     G->chanx = next_chan(G);
                ^~~~~~~~~
In file included from bully.c:91:0:
iface.c: In function ‘set_chan’:
iface.c:28:9: warning: implicit declaration of function ‘set_chanx’ [-Wimplicit-function-declaration]
  return set_chanx(G, G->index[chan]);
         ^~~~~~~~~
bully.c: In function ‘main’:
bully.c:969:4: warning: ‘return’ with no value, in function returning non-void
    return;
    ^~~~~~
bully.c:95:5: note: declared here
 int main(int argc, char *argv[])
     ^~~~
Makefile:19: recipe for target 'bully' failed
make: *** [bully] Error 1
========END ERROR LOG========

Additional info:
1. installed latest Kali-rolling versions of libpcap-dev, libssl-dev, build-essential, aircrack-ng, and pixiewps.
2. Pixiewps built successfully from required Git host Wiire, and installed before Bully's make attempt.
3. Using GNU make v 4.1 as provided with Kali 4.8.0-amd64.
5. Bully cloned from Git master on 26 Jan 2017, 11 PM CST.
6. Make was run as root (as can be seen in the log).

I will try running make as a non-root admin user to see if that makes a difference, and post a pass/fail or new errors.

**Comment by boinkitsbroken** [comment]
Update:

The errors are identical under a non-root user, even when using 'make' instead of 'sudo make'.  Whatever the problem is, it's not dependent on the build environment's root-ness. My guess is the GNU make interpreter is expecting a different syntax in the makefile. 

Do you have a suggested or recommended version of make to use when building bully? Perhaps some different headers I should be using?

**Comment by lloydXmas** [comment]
The issue may be due to the fact that the OpenSSL library used when this was last updated is outdated. Do the headers in crypto_openssl.c conflict with the current OpenSSL version?

**Comment by 0MazaHacka0** [comment]
Same here. Using Kali Linux 2016.1 with last updates

**Comment by m0j4r115** [comment]
Having same errors. Using Kali 2016.2 clean install, fully updated.

**Comment by lloydXmas** [comment]
It's probably due to API changes in newer versions of openssl that cause the compile to fail. What version of openssl are you running? `openssl version -v`

If you only have something like 1.1.0 then you probably also have the libssl 1.1 development libraries which cause these errors. You can check your library version with ldconfig:
`ldconfig -p | grep libssl`  

If you only see libssl.so.1.1 try: 
`apt-get install libssl1.0-dev`

Run `make clean` and `make` again

**Comment by m0j4r115** [comment]
That was indeed the problem. Thank you.

**Comment by carlosnewmusic** [comment]
cc -I`pwd` -I`pwd`/utils/ -I`pwd`/tls/ -I`pwd`/wps/ -I`pwd`/crypto/ -I`pwd`/common/ -o bully bully.c -lpcap -lssl -lcrypto
In file included from bully.c:65:0:
crypto/crypto_openssl.c: In function 'openssl_digest_vector':
crypto/crypto_openssl.c:81:13: error: storage size of 'ctx' isn't known
  EVP_MD_CTX ctx;
             ^~~
crypto/crypto_openssl.c: In function 'rc4_skip':
crypto/crypto_openssl.c:148:17: error: storage size of 'ctx' isn't known
  EVP_CIPHER_CTX ctx;
                 ^~~
crypto/crypto_openssl.c: At top level:
crypto/crypto_openssl.c:301:17: error: field 'enc' has incomplete type
  EVP_CIPHER_CTX enc;
                 ^~~
crypto/crypto_openssl.c:302:17: error: field 'dec' has incomplete type
  EVP_CIPHER_CTX dec;
                 ^~~
crypto/crypto_openssl.c: In function 'dh5_init':
crypto/crypto_openssl.c:426:4: error: dereferencing pointer to incomplete type 'DH {aka struct dh_st}'
  dh->g = BN_new();
    ^~
In file included from bully.c:89:0:
80211.c: In function 'reassoc':
80211.c:328:16: warning: implicit declaration of function 'set_chan' [-Wimplicit-function-declaration]
     G->chanx = set_chan(G, tag->data[0]);
                ^~~~~~~~
80211.c:356:16: warning: implicit declaration of function 'next_chan' [-Wimplicit-function-declaration]
     G->chanx = next_chan(G);
                ^~~~~~~~~
In file included from bully.c:91:0:
iface.c: In function 'set_chan':
iface.c:28:9: warning: implicit declaration of function 'set_chanx' [-Wimplicit-function-declaration]
  return set_chanx(G, G->index[chan]);
         ^~~~~~~~~
bully.c: In function 'main':
bully.c:969:4: warning: 'return' with no value, in function returning non-void
    return;
    ^~~~~~
bully.c:95:5: note: declared here
 int main(int argc, char *argv[])
     ^~~~
Makefile:19: fallo en las instrucciones para el objetivo 'bully'
make: *** [bully] Error 1

**Comment by wiire** [comment]
Now (ea0cdd9) it should compile with the previous version of OpenSSL (`libssl1.0-dev`).

Please refer to #12.

**Comment by philiplambok** [comment]
> It's probably due to API changes in newer versions of openssl that cause the compile to fail. What version of openssl are you running? `openssl version -v`
> 
> If you only have something like 1.1.0 then you probably also have the libssl 1.1 development libraries which cause these errors. You can check your library version with ldconfig:
> `ldconfig -p | grep libssl`
> 
> If you only see libssl.so.1.1 try:
> `apt-get install libssl1.0-dev`
> 
> Run `make clean` and `make` again

OOO Thank you Sir!
