### ISSUE TITLE
new git release tag

### ISSUE THREAD

**Issue by anthraxx** [aanarchyy/bully#15]
Hi. since the commits seem quite static now and nothing is seriously broken it would be awesome to get a new release tag that drops the openssl dependency. that would be super awesome for packaging.
cheers

**Comment by aanarchyy** [comment]
Just did that right now, but thanks for reminding me i wanted to do that :-)

**Comment by anthraxx** [comment]
@aanarchyy awwww thats "just" an 1.1 that needs openssl :crying_cat_face: when do you plan one without openssl? :yum:

**Comment by OscarAkaElvis** [comment]
Yeah, openssl dependency was removed but version is still 1.1. IDK if release a version 1.2 only with that change could be good idea because there is no new features. Maybe a 1.2 version with a little improvement like proposed on this issue: https://github.com/aanarchyy/bully/issues/4
