### ISSUE TITLE
Wps pin not found

### ISSUE THREAD

**Issue by Chin0p** [aanarchyy/bully#16]
Hi sir, I'm getting an error where it says "WPS PIN not found". So I just wanna ask u where is all the information saved if I want to check all the received hashes.

**Comment by soxrok2212** [comment]
It is not saved anywhere. Use verbose output and get all the information you need from that.

**Comment by Chin0p** [comment]
Hi sir, actually I'm new to kali linux so can u please tell me how to use verbose output. Thanks
