### ISSUE TITLE
The pin generator repeats the same pin

### ISSUE THREAD

**Issue by Machadoassiss** [aanarchyy/bully#18]
Good afternoon

I am doing a security test and the bully pin generator keeps repeating the same pin number indefinitely, not generating a new pin.
Do you know if there is a configuration problem, is it missing a patch?
I'm using a version of Bully.

Here is the error:

[!] Restoring session from '/root/.bully/4432c8a1d2f2.run'
[+] Index of starting pin number is '0000000'
[+] Last State = 'NoAssoc' Next pin '35150039'
[!] Received disassociation / deauthentication from the AP
[+] Rx (M1) = 'NoAssoc' Next pin '35150039'
[!] Received disassociation / deauthentication from the AP
[+] Rx (Auth) = 'NoAssoc' Next pin '35150039'
[!] Received disassociation / deauthentication from the AP
[+] Rx (M1) = 'NoAssoc' Next pin '35150039'
[!] Received disassociation / deauthentication from the AP
[+] Tx (DeAuth) = 'NoAssoc' Next pin '35150039'
[!] Received disassociation / deauthentication from the AP
[+] Rx (M1) = 'NoAssoc' Next pin '35150039'

Please help me.

**Comment by Gartral** [comment]
this issue is affecting me as well
options are bully mon0 -b XX:XX:XX:XX:XX:XX -N -c N -d  -v 4  on bully 1.1 against known vulnerable  Netgear router based on a Broadcom chipset with WPS 1.0

**Comment by azamet90** [comment]
same -.- i better remove it

**Comment by soxrok2212** [comment]
You're either too far away, WPS is disabled, there is MAC filtering, or WPS is enabled but not configured.

**Comment by azamet90** [comment]
> You're either too far away, WPS is disabled, there is MAC filtering, or WPS is enabled but not configured.

im not too far im testing it on my self wps is enabled there is no mac filtering wps is on default settings

**Comment by soxrok2212** [comment]
Try rebooting the router, double checking the web GUI to see that PIN mode is enabled (not just push button) and provide the correct pin. Then report back
