### ISSUE TITLE
how to install on mac??

### ISSUE THREAD

**Issue by kingxiaofire** [aanarchyy/bully#19]
--- bully/src ‹master› » make
cc -I`pwd` -I`pwd`/utils/ -I`pwd`/tls/ -I`pwd`/wps/ -I`pwd`/crypto/ -I`pwd`/common/ -DUSE_INTERNAL_CRYPTO -DCONFIG_NO_RANDOM_POOL -o bully bully.c -lpcap
bully.c:27:10: fatal error: 'linux/if_ether.h' file not found
#include <linux/if_ether.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [bully] Error 1

**Comment by soxrok2212** [comment]
macOS is not supported.
