### ISSUE TITLE
It can`t make install in Termux

### ISSUE THREAD

**Issue by CWSHBR** [aanarchyy/bully#22]
$ tsudo make install
install -d /usr/local/bin      
install: cannot create directory ‘/usr’: Read-only file system
make: *** [Makefile:31: install] Error 1
I tried to edit Makefile, doesn`t help

**Comment by kimocoder** [comment]
mount -o remount,rw /system

Then go again

**Comment by CWSHBR** [comment]
@kimocoder, mount: '/system' not in /proc/mounts
