### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by 0xFF1E071F** [aanarchyy/bully#23]
Can you please tag a new release. I am making linux packages for Pisi Linux and i need a updated download link from your repos releases archive.
Thank you =)

**Comment by peterhoeg** [comment]
Same for nixos although we're using the latest commit.

https://github.com/NixOS/nixpkgs/pull/91386

**Comment by peterhoeg** [comment]
@0xFF1E071F, we are just using the kimocoder fork instead as it's maintained.

**Comment by 0xFF1E071F** [comment]
Thank you @peterhoeg i am going to check kimocoder's tags!

BTW @aanarchyy we are still waiting for your 'tag update'

**Comment by 0xFF1E071F** [comment]
> @0xFF1E071F, we are just using the kimocoder fork instead as it's maintained.

@peterhoeg Thank you again, i have compiled and tried kimcoders latest tag. It is compiling and working =)

**Comment by soxrok2212** [comment]
https://github.com/aanarchyy/bully/releases/tag/1.2
