### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by steelbrain** [aanarchyy/bully#3]
Just like the title says. Reaver supports mac, would be nice to have bully support it too

**Comment by xKillerByte** [comment]
I've got a mac computer too.
Can you help me with this error?
Here is the log:
`cc` -I`pwd` -I`pwd`/utils/ -I`pwd`/tls/ -I`pwd`/wps/ -I`pwd`/crypto/ -I`pwd`/common/ -o bully bully.c -lpcap -lssl -lcrypto
bully.c:27:10: fatal error: 'linux/if_ether.h' file not found
#include `<linux/if_ether.h>`

**Comment by soxrok2212** [comment]
macOS does **NOT** support Reaver. While it may compile, the drivers do not support injection in monitor mode and fail. There is no purpose in having this run on macOS, just install a Linux distribution in a virtual machine and use a USB wireless card.
