### ISSUE TITLE
Another make error? 

### ISSUE THREAD

**Issue by statdev** [aanarchyy/bully#7]
Didnt get a single hit searching. I installed the dependencies via apt, built the master of pixie, and reinstalled libpcap for kicks. 

#make
cc -I`pwd` -I`pwd`/utils/ -I`pwd`/tls/ -I`pwd`/wps/ -I`pwd`/crypto/ -I`pwd`/common/ -o bully bully.c -lpcap -lssl -lcrypto
In file included from bully.c:65:0:
crypto/crypto_openssl.c: In function ‘openssl_digest_vector’:
crypto/crypto_openssl.c:81:13: error: storage size of ‘ctx’ isn’t known
  EVP_MD_CTX ctx;
             ^~~
crypto/crypto_openssl.c: In function ‘rc4_skip’:
crypto/crypto_openssl.c:148:17: error: storage size of ‘ctx’ isn’t known
  EVP_CIPHER_CTX ctx;
                 ^~~
crypto/crypto_openssl.c: At top level:
crypto/crypto_openssl.c:301:17: error: field ‘enc’ has incomplete type
  EVP_CIPHER_CTX enc;
                 ^~~
crypto/crypto_openssl.c:302:17: error: field ‘dec’ has incomplete type
  EVP_CIPHER_CTX dec;
                 ^~~
crypto/crypto_openssl.c: In function ‘dh5_init’:
crypto/crypto_openssl.c:426:4: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
  dh->g = BN_new();
    ^~
In file included from bully.c:89:0:
80211.c: In function ‘reassoc’:
80211.c:328:16: warning: implicit declaration of function ‘set_chan’ [-Wimplicit-function-declaration]
     G->chanx = set_chan(G, tag->data[0]);
                ^~~~~~~~
80211.c:356:16: warning: implicit declaration of function ‘next_chan’ [-Wimplicit-function-declaration]
     G->chanx = next_chan(G);
                ^~~~~~~~~
In file included from bully.c:91:0:
iface.c: In function ‘set_chan’:
iface.c:28:9: warning: implicit declaration of function ‘set_chanx’ [-Wimplicit-function-declaration]
  return set_chanx(G, G->index[chan]);
         ^~~~~~~~~
bully.c: In function ‘main’:
bully.c:969:4: warning: ‘return’ with no value, in function returning non-void
    return;
    ^~~~~~
bully.c:95:5: note: declared here
 int main(int argc, char *argv[])
     ^~~~
Makefile:19: recipe for target 'bully' failed
make: *** [bully] Error 1

**Comment by qwertyforce** [comment]
Same problem

**Comment by hellfi** [comment]
With an older **libssl-dev**_1.0.2j-1_ bully compiles, with the current _1.1.0c-2_ it errors out as seen above.
Kali as of now includes the wrong version of libssl-dev for this, thanks to rolling release (I might be wrong?) there is only the new version in the repository

**Comment by qwertyforce** [comment]
Do you know how to install older version of  libssl-dev?  I have the same problem.

**Comment by Gritsenich** [comment]
Try this (work for me):
1) apt remove libssl-dev
2) download [libssl1.0.0_1.0.1t](http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u5_amd64.deb)
3) sudo dpkg -i /root/Downloads/libssl1.0.0_1.0.1t-1+deb8u5_amd64.deb

**Comment by wiire** [comment]
Now (ea0cdd9) it should compile with the previous version of OpenSSL (`libssl1.0-dev`).

Please refer to #12.
