### ISSUE TITLE
Make Error message. 

### ISSUE THREAD

**Issue by Malachai777** [aanarchyy/bully#8]
Just wanted to install bully but received 'Make' error . I did install the repo for the software. 

~/bully/src# apt-get -y install build-essential libpcap-dev libssl-dev aircrack-ng pixiewps
Reading package lists... Done
Building dependency tree       
Reading state information... Done
aircrack-ng is already the newest version (1:1.2-0~rc4-1).
build-essential is already the newest version (12.2).
libpcap-dev is already the newest version (1.8.1-3).
libssl-dev is already the newest version (1.1.0c-2).
pixiewps is already the newest version (1.2.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

:~/bully/src# make
cc -I`pwd` -I`pwd`/utils/ -I`pwd`/tls/ -I`pwd`/wps/ -I`pwd`/crypto/ -I`pwd`/common/ -o bully bully.c -lpcap -lssl -lcrypto
In file included from bully.c:65:0:
crypto/crypto_openssl.c: In function ‘openssl_digest_vector’:
crypto/crypto_openssl.c:81:13: error: storage size of ‘ctx’ isn’t known
  EVP_MD_CTX ctx;
             ^~~
crypto/crypto_openssl.c: In function ‘rc4_skip’:
crypto/crypto_openssl.c:148:17: error: storage size of ‘ctx’ isn’t known
  EVP_CIPHER_CTX ctx;
                 ^~~
crypto/crypto_openssl.c: At top level:
crypto/crypto_openssl.c:301:17: error: field ‘enc’ has incomplete type
  EVP_CIPHER_CTX enc;
                 ^~~
crypto/crypto_openssl.c:302:17: error: field ‘dec’ has incomplete type
  EVP_CIPHER_CTX dec;
                 ^~~
crypto/crypto_openssl.c: In function ‘dh5_init’:
crypto/crypto_openssl.c:426:4: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
  dh->g = BN_new();
    ^~
In file included from bully.c:89:0:
80211.c: In function ‘reassoc’:
80211.c:328:16: warning: implicit declaration of function ‘set_chan’ [-Wimplicit-function-declaration]
     G->chanx = set_chan(G, tag->data[0]);
                ^~~~~~~~
80211.c:356:16: warning: implicit declaration of function ‘next_chan’ [-Wimplicit-function-declaration]
     G->chanx = next_chan(G);
                ^~~~~~~~~
In file included from bully.c:91:0:
iface.c: In function ‘set_chan’:
iface.c:28:9: warning: implicit declaration of function ‘set_chanx’ [-Wimplicit-function-declaration]
  return set_chanx(G, G->index[chan]);
         ^~~~~~~~~
bully.c: In function ‘main’:
bully.c:969:4: warning: ‘return’ with no value, in function returning non-void
    return;
    ^~~~~~
bully.c:95:5: note: declared here
 int main(int argc, char *argv[])
     ^~~~
Makefile:19: recipe for target 'bully' failed
make: *** [bully] Error 1

**Comment by FightingForFun** [comment]
Now clone... make... 
root@0x01:~/bully/src# make
cc -I`pwd` -I`pwd`/utils/ -I`pwd`/tls/ -I`pwd`/wps/ -I`pwd`/crypto/ -I`pwd`/common/ -o bully bully.c -lpcap -lssl -lcrypto
In file included from bully.c:65:0:
crypto/crypto_openssl.c:16:30: fatal error: openssl/opensslv.h: No such file or directory
 #include <openssl/opensslv.h>
                              ^
compilation terminated.
Makefile:19: recipe for target 'bully' failed
make: *** [bully] Error 1
root@0x01:~/bully/src#

**Comment by Malachai777** [comment]
Is there any solution to this problem? Has anyone run into this problem trying to install it?

**Comment by FightingForFun** [comment]
i install reinstall libssl and openssl... when i again make 
make
cc -I`pwd` -I`pwd`/utils/ -I`pwd`/tls/ -I`pwd`/wps/ -I`pwd`/crypto/ -I`pwd`/common/ -o bully bully.c -lpcap -lssl -lcrypto
In file included from bully.c:65:0:
crypto/crypto_openssl.c: In function ‘openssl_digest_vector’:
crypto/crypto_openssl.c:81:13: error: storage size of ‘ctx’ isn’t known
  EVP_MD_CTX ctx;
             ^~~
crypto/crypto_openssl.c: In function ‘rc4_skip’:
crypto/crypto_openssl.c:148:17: error: storage size of ‘ctx’ isn’t known
  EVP_CIPHER_CTX ctx;
                 ^~~
crypto/crypto_openssl.c: At top level:
crypto/crypto_openssl.c:301:17: error: field ‘enc’ has incomplete type
  EVP_CIPHER_CTX enc;
                 ^~~
crypto/crypto_openssl.c:302:17: error: field ‘dec’ has incomplete type
  EVP_CIPHER_CTX dec;
                 ^~~
crypto/crypto_openssl.c: In function ‘dh5_init’:
crypto/crypto_openssl.c:426:4: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
  dh->g = BN_new();
    ^~
In file included from bully.c:89:0:
80211.c: In function ‘reassoc’:
80211.c:328:16: warning: implicit declaration of function ‘set_chan’ [-Wimplicit-function-declaration]
     G->chanx = set_chan(G, tag->data[0]);
                ^~~~~~~~
80211.c:356:16: warning: implicit declaration of function ‘next_chan’ [-Wimplicit-function-declaration]
     G->chanx = next_chan(G);
                ^~~~~~~~~
In file included from bully.c:91:0:
iface.c: In function ‘set_chan’:
iface.c:28:9: warning: implicit declaration of function ‘set_chanx’ [-Wimplicit-function-declaration]
  return set_chanx(G, G->index[chan]);
         ^~~~~~~~~
bully.c: In function ‘main’:
bully.c:969:4: warning: ‘return’ with no value, in function returning non-void
    return;
    ^~~~~~
bully.c:95:5: note: declared here
 int main(int argc, char *argv[])
     ^~~~
Makefile:19: recipe for target 'bully' failed
make: *** [bully] Error 1

Kali Linux 2016.2 dist and gems updated

**Comment by BKDOnions** [comment]
I got a same problem,anyone know how to fix it???ubuntu 16.04Lts

**Comment by carlosnewmusic** [comment]
![captura de pantalla_](https://cloud.githubusercontent.com/assets/19379457/24082942/43960828-0cce-11e7-8d58-318cb7f0be28.png) :/

**Comment by OscarAkaElvis** [comment]
Did you tried downgrading libssl-dev ??? I mean, `apt-get remove libssl-dev && apt-get install libssl1.0-dev`.

**Comment by wiire** [comment]
Now (ea0cdd9) it should compile with the previous version of OpenSSL (`libssl1.0-dev`).

Please refer to #12.
